### ISSUE TITLE
Non buildable with GHC-7.8

### ISSUE THREAD

**Issue by phadej** [JanGe/irc-dcc#1]
```
src/Network/IRC/DCC/Internal.hs:326:30:
    Not in scope: ‘mempty’
    Perhaps you meant ‘empty’ (imported from Control.Applicative)
```

Please:
- either bump base lower bound (no new release are required, as I made a revisions on Hackage)
- correct the package, you may use [`base-compat`](http://hackage.haskell.org/package/base-compat) for example (I see you don't test GHC-7.8 in your travis setup, that would catch similar issues in the future)

_EDIT:_ same applies to https://github.com/JanGe/xdcc, I'm not sure whether it would build with GHC-7.8, when `irc-dcc` is fixed

**Comment by JanGe** [comment]
Do you have a use case for this library (or `xdcc`) with GHC 7.8?
If yes, I will look into making it compatible.

**Comment by phadej** [comment]
I don't need this library at al. I'm was going thru [`matrix.h.h.o`](http://matrix.hackage.haskell.org/package/irc-dcc) builds of recent Stackage additions. If you are not planning to support _GHC-7.8_, bump the base lower-bound to `base >= 4.8`

**Comment by JanGe** [comment]
Thanks for the hint @phadej :)

For now I will stick with bumping up the lower bound. If someone else needs support for GHC <= 7.8, please reopen this issue.
